// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IndustrialSolutions.Models.Entities;

public partial class EmailAttachment
{
    public int Id { get; set; }

    public int EmailId { get; set; }

    public string AttachmentId { get; set; }

    public string FileName { get; set; }

    public long SizeBytes { get; set; }

    public string ContentType { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Email Email { get; set; }
}