// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IndustrialSolutions.Models.Entities;

public partial class Email
{
    public int Id { get; set; }

    public string UniqueEmailId { get; set; }

    public long GmailUid { get; set; }

    public string Folder { get; set; }

    public string FromName { get; set; }

    public string FromEmail { get; set; }

    public string Subject { get; set; }

    public string Snippet { get; set; }

    public DateTime ReceivedUtc { get; set; }

    public string ReceivedLocal { get; set; }

    public bool Unread { get; set; }

    public bool HasAttachments { get; set; }

    public string HtmlBody { get; set; }

    public string TextBody { get; set; }

    public string LabelsJson { get; set; }

    public string Company { get; set; }

    public string Phone { get; set; }

    public string GstNumber { get; set; }

    public string Message { get; set; }

    public bool IsContactForm { get; set; }

    public DateTime CreatedAt { get; set; }

    public DateTime UpdatedAt { get; set; }

    public virtual ICollection<EmailAttachment> EmailAttachments { get; set; } = new List<EmailAttachment>();
}