// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using IndustrialSolutions.Models.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace IndustrialSolutions.Models.Entities
{
    public partial interface IIndustrialSolutionsEmailsContextProcedures
    {
        Task<List<sp_CleanupOldEmailsResult>> sp_CleanupOldEmailsAsync(int? daysToKeep, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<sp_GetEmailStatsResult>> sp_GetEmailStatsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
