// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using IndustrialSolutions.Models.Entities;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace IndustrialSolutions.Models.Entities
{
    public partial class IndustrialSolutionsEmailsContext
    {
        private IIndustrialSolutionsEmailsContextProcedures _procedures;

        public virtual IIndustrialSolutionsEmailsContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new IndustrialSolutionsEmailsContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public IIndustrialSolutionsEmailsContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class IndustrialSolutionsEmailsContextProcedures : IIndustrialSolutionsEmailsContextProcedures
    {
        private readonly IndustrialSolutionsEmailsContext _context;

        public IndustrialSolutionsEmailsContextProcedures(IndustrialSolutionsEmailsContext context)
        {
            _context = context;
        }

        public virtual async Task<List<sp_CleanupOldEmailsResult>> sp_CleanupOldEmailsAsync(int? daysToKeep, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                new SqlParameter
                {
                    ParameterName = "DaysToKeep",
                    Value = daysToKeep ?? Convert.DBNull,
                    SqlDbType = System.Data.SqlDbType.Int,
                },
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_CleanupOldEmailsResult>("EXEC @returnValue = [dbo].[sp_CleanupOldEmails] @DaysToKeep = @DaysToKeep", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }

        public virtual async Task<List<sp_GetEmailStatsResult>> sp_GetEmailStatsAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<sp_GetEmailStatsResult>("EXEC @returnValue = [dbo].[sp_GetEmailStats]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
