// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace IndustrialSolutions.Models.Entities
{
    public partial class sp_GetEmailStatsResult
    {
        public int? TotalEmails { get; set; }
        public int? ContactForms { get; set; }
        public int? UnreadEmails { get; set; }
        public int? EmailsWithAttachments { get; set; }
        public DateTime? LastEmailReceived { get; set; }
        public int? EmailsLastWeek { get; set; }
    }
}
