// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IndustrialSolutions.Models.Entities;

public partial class VwContactFormEmail
{
    public int Id { get; set; }

    public string UniqueEmailId { get; set; }

    public long GmailUid { get; set; }

    public string FromName { get; set; }

    public string FromEmail { get; set; }

    public string Subject { get; set; }

    public string Company { get; set; }

    public string Phone { get; set; }

    public string GstNumber { get; set; }

    public string Message { get; set; }

    public DateTime ReceivedUtc { get; set; }

    public string ReceivedLocal { get; set; }

    public bool Unread { get; set; }

    public bool HasAttachments { get; set; }

    public int? AttachmentCount { get; set; }
}